apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: attractive-condor-python 
  janus-idp.io/tekton: attractive-condor-python
  backstage.io/kubernetes-id: attractive-condor-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: attractive-condor-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  